// node tools/tests/test-contact.js (combined site)  -> file:// checks for the ارتباط با مدیران form
const { chromium } = require('playwright-core'); const path = require('path');
(async () => {
  const b = await chromium.launch({ executablePath: '/usr/bin/google-chrome' });
  const pg = await b.newPage({ viewport: { width: 1366, height: 900 } });
  const errs = []; pg.on('pageerror', e => errs.push(e.message)); pg.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
  await pg.goto('file://' + path.resolve(__dirname, '../../index.html'), { waitUntil: 'load' });
  await pg.evaluate(() => document.fonts.ready);
  require('fs').mkdirSync(path.resolve(__dirname, '../../out/interactive'), { recursive: true });
  const R = []; const ok = (n, c) => { R.push([n, !!c]); };
  const H = await pg.evaluate(() => document.documentElement.scrollHeight); ok('page height 4306 (' + H + ')', H === 4306);
  const bg = await pg.evaluate(() => ['.mc-panel', '.mc-card'].map(s => { const e = document.querySelector(s), r = e.getBoundingClientRect(); return [getComputedStyle(e).backgroundImage.slice(0, 60), r.x, r.y + scrollY, r.width, r.height]; }));
  ok('panel at 50,2781 804x390 ' + JSON.stringify(bg[0].slice(1)), bg[0][1] === 50 && bg[0][2] === 2781 && bg[0][3] === 804);
  ok('card at 884,2780 432x393', bg[1][1] === 884 && bg[1][2] === 2780 && bg[1][3] === 432);
  const loaded = await pg.evaluate(() => Promise.all(['assets/mayor/panel.png', 'assets/mayor/card.png'].map(u => new Promise(r => { const i = new Image(); i.onload = () => r(i.naturalWidth); i.onerror = () => r(0); i.src = u; }))));
  ok('bg images load via file:// ' + loaded, loaded.every(w => w > 0));
  await pg.click('#mc-name'); await pg.waitForTimeout(300); const fb = await pg.$eval('#mc-name', e => getComputedStyle(e).borderColor); ok('focus border gold ' + fb, fb === 'rgb(220, 178, 89)');
  await pg.click('.mc-btn'); await pg.waitForTimeout(100);
  let st = await pg.$eval('.mc-ok', e => [e.textContent, e.className]); ok('empty submit -> error, no success', /کامل/.test(st[0]) && st[1].includes('is-err'));
  ok('invalid fields flagged', await pg.$$eval('.mc-form :invalid', l => l.length) >= 5);
  await pg.fill('#mc-name', 'علی رضایی');
  await pg.click('#mc-phone'); await pg.keyboard.type('۰۹۱۲۳۴۵۶۷۸۹');
  ok('persian digits normalised', (await pg.$eval('#mc-phone', e => e.value)) === '09123456789');
  await pg.selectOption('#mc-dept', { index: 2 }); await pg.selectOption('#mc-cat', { index: 1 });
  await pg.fill('#mc-msg', 'سلام، لطفا وضعیت آسفالت خیابان را بررسی کنید.');
  await pg.click('.mc-btn'); await pg.waitForTimeout(100);
  st = await pg.$eval('.mc-ok', e => [e.textContent, e.className]); ok('valid submit -> success msg', /موفقیت/.test(st[0]) && !st[1].includes('is-err') && st[1].includes('is-on'));
  ok('form reset after submit', (await pg.$eval('#mc-name', e => e.value)) === '');
  ok('url unchanged (preventDefault)', !pg.url().includes('?'));
  await pg.click('label[data-id="403:142"] span'); ok('anonymous disables name', await pg.$eval('#mc-name', e => e.disabled && !e.required));
  await pg.click('.mc-msgbtn'); await pg.waitForTimeout(600);
  ok('پیام شهردار -> dept preset + textarea focus', await pg.evaluate(() => document.querySelector('#mc-dept').value === 'دفتر شهردار' && document.activeElement.id === 'mc-msg'));
  ok('labels bound', await pg.$$eval('.mc-form input:not([type=checkbox]),.mc-form select,.mc-form textarea', l => l.every(e => e.labels.length)));
  // public messages line: static + tight when it fits, marquee (paused on hover) only on overflow
  const tk = await pg.evaluate(() => { const t = document.querySelector('.mc-tick'); const v = [...t.querySelectorAll('.mc-tg:not([aria-hidden]) > *')].filter(e => e.offsetWidth).map(e => e.getBoundingClientRect());
    return { m: t.classList.contains('is-marquee'), n: v.length, g1: v[0].left - v[1].right, g2: v[1].left - v[2].right, d: v[1].width, a: getComputedStyle(t.querySelector('.mc-track')).animationName }; });
  ok('messages static side by side ' + JSON.stringify(tk), !tk.m && tk.n === 3 && tk.a === 'none');
  ok('tight separator 6|4|6px', Math.abs(tk.g1 - 6) < 0.6 && Math.abs(tk.g2 - 6) < 0.6 && Math.abs(tk.d - 4) < 0.1);
  await pg.evaluate(() => { document.querySelector('.mc-tick').style.width = '400px'; dispatchEvent(new Event('resize')); });
  await pg.waitForTimeout(2300);
  const mq = await pg.evaluate(() => { const t = document.querySelector('.mc-tick'); return [t.classList.contains('is-marquee'), getComputedStyle(t.querySelector('.mc-track')).animationName]; });
  await pg.hover('.mc-tick'); await pg.waitForTimeout(100);
  const ps = await pg.$eval('.mc-track', e => getComputedStyle(e).animationPlayState);
  ok('overflow -> marquee, paused on hover ' + mq + ' ' + ps, mq[0] && mq[1] === 'mc-tick' && ps === 'paused');
  ok('no JS errors ' + errs.join('|'), errs.length === 0);
  await pg.goto('file://' + path.resolve(__dirname, '../../index.html'), { waitUntil: 'load' });
  await pg.evaluate(() => window.scrollTo(0, 2680)); await pg.click('.mc-btn'); await pg.waitForTimeout(300);
  await pg.screenshot({ path: path.resolve(__dirname, '../../out/interactive/contact-invalid.png'), clip: { x: 0, y: 60, width: 1366, height: 460 } });
  for (const [n, c] of R) console.log(c ? 'PASS' : 'FAIL', n);
  console.log(R.filter(r => r[1]).length + '/' + R.length);
  await b.close();
})();
